# Generated by Django 4.2.5 on 2023-09-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Название альбома")),
                ("year", models.PositiveSmallIntegerField(verbose_name="Дата выпуска альбома")),
            ],
            options={
                "verbose_name": "Альбом",
                "verbose_name_plural": "Альбомы",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AlbumTrack",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.PositiveSmallIntegerField(verbose_name="Порядковый номер в альбоме")),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="album_tracks", to="catalog.album"
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Название исполнителя")),
            ],
            options={
                "verbose_name": "Исполнитель",
                "verbose_name_plural": "Исполнители",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Название песни")),
                (
                    "albums",
                    models.ManyToManyField(related_name="tracks", through="catalog.AlbumTrack", to="catalog.album"),
                ),
            ],
            options={
                "verbose_name": "Песня",
                "verbose_name_plural": "Песни",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="albumtrack",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="track_albums", to="catalog.track"
            ),
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="albums",
                to="catalog.artist",
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AddConstraint(
            model_name="albumtrack",
            constraint=models.UniqueConstraint(fields=("track", "order"), name="unique_track_order"),
        ),
        migrations.AddConstraint(
            model_name="albumtrack",
            constraint=models.UniqueConstraint(fields=("track", "album"), name="unique_track_album"),
        ),
        migrations.AddConstraint(
            model_name="albumtrack",
            constraint=models.UniqueConstraint(fields=("order", "album"), name="unique_order_album"),
        ),
    ]
